BB_DATASET_PATH = '/path/to/fsoco_bounding_boxes_train'
BB_IMAGES = '/path/to/full/images'
BB_ANNOTATIONS = '/path/to/full/annotations'
BB_OBJECTS = '/path/to/full/processed'
BB_TARGET = '/path/to/full/target'
